apiVersion: v1
kind: Pod
metadata:
  name: awscli
spec:
  containers:
    - name: awscli
      # TODO: Replace the image with an official one once Amazon  publishes theirs
      image: mikesir87/aws-cli:1.16.220
      stdin: true
      tty: true
      volumeMounts:
        - name: cosi-secrets
          mountPath: /data/cosi
          readOnly: true
  volumes:
  - name: cosi-secrets
    secret:
      secretName: ba-secret
