kind: BucketClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: sample-bcc
driverName: ceph.objectstorage.k8s.io
deletionPolicy: Delete
parameters:
  ObjectStoreUserSecretName: rook-ceph-object-user-my-store-my-user
  ObjectStoreUserSecretNamespace: rook-ceph
